version: '3.8'
services:
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  web:
    image: acesandev/recipes-kiii-image:latest
    command: gunicorn --bind 0.0.0.0:8000 Recipes.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: mongodb://db:27017/recipes

volumes:
  mongodb_data:
