apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  namespace: projects-kiii
data:
  MONGO_INITDB_DATABASE: "kiii"
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: projects-kiii
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: bW9uZ29hZG1pbg==
  MONGO_INITDB_ROOT_PASSWORD: cGFzc3dvcmQ=
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongodb-db-pvc
  namespace: projects-kiii
  labels:
    app: mongodb
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: projects-kiii
spec:
  serviceName: "mongodb"
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:4.4
          ports:
            - containerPort: 27017
              name: mongodb
          env:
            - name: MONGO_INITDB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mongodb-config
                  key: MONGO_INITDB_DATABASE
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGO_INITDB_ROOT_PASSWORD
          volumeMounts:
            - name: mongodb-persistent-storage
              mountPath: /data/db
      volumes:
        - name: mongodb-persistent-storage
          persistentVolumeClaim:
            claimName: mongodb-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: projects-kiii
spec:
  ports:
    - port: 27017
      name: mongodb
      protocol: TCP
  selector:
    app: mongodb
