apiVersion: v1
kind: ConfigMap
metadata:
  name: recipes-config
  namespace: recipes-kiii
data:
  POSTGRES_DB: "kiii"
  POSTGRES_HOST: "database"
  POSTGRES_URL: "postgres-service.recipes-kiii.svc.cluster.local"
---
apiVersion: v1
kind: Secret
metadata:
  name: recipes-secret
  namespace: recipes-kiii
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: YWRtaW4=
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: recipes-kiii
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipes
  namespace: recipes-kiii
spec:
  replicas: 3
  selector:
    matchLabels:
      app: recipes
  template:
    metadata:
      labels:
        app: recipes
    spec:
      containers:
        - name: recipes
          image: acesandev/recipes-kiii-image:latest
          ports:
            - containerPort: 8000
          env:
            - name: POSTGRES_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: recipes-config
                  key: POSTGRES_DB
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: recipes-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: recipes-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_URL
              valueFrom:
                configMapKeyRef:
                  name: recipes-config
                  key: POSTGRES_URL
            - name: DATABASE_URL
              value: "postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_URL):5432/$(POSTGRES_DB)"
          envFrom:
            - configMapRef:
                name: recipes-config
            - secretRef:
                name: recipes-secret