# Generated by Django 5.0.3 on 2024-09-05 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipesApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='type_of_meal',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dessert', 'Dessert'), ('Dinner', 'Dinner')], default=0, max_length=14),
            preserve_default=False,
        ),
    ]
