# Generated by Django 4.1.13 on 2024-09-21 14:03

import RecipesApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipesApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='id',
            field=models.CharField(default=RecipesApp.models.generate_object_id, max_length=24, primary_key=True, serialize=False),
        ),
    ]
