# Generated by Django 5.0.3 on 2024-09-05 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecipesApp', '0002_recipe_type_of_meal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='type_of_meal',
        ),
    ]
